---
name: Bug
description: Something isn't working as expected.
labels:
  - "Type: Fix"
  - "Status: Planned"
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Steps + expected vs actual.
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Version, system, or logs.
