---
name: Chore
description: Maintenance, cleanup, or non-functional changes.
title: "[Chore]: "
labels:
  - "Type: Chore"
assignees:
  - TordLoefgren

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs doing and why.
    validations:
      required: true
