---
name: Feature
description: Add or improve functionality.
labels:
  - "Type: Feature"
  - "Status: Planned"
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What should this feature do?
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ] Implementation
        - [ ] Test
        - [ ] Docs
