---
name: Feature
description: Add or improve functionality.
title: "[Feature]: "
labels:
  - "Type: Feature"
assignees:
  - TordLoefgren

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this feature do and why is it valuable?
    validations:
      required: true
