---
name: Fix
description: Something isn't working as expected.
title: "[Fix]: "
labels:
  - "Type: Fix"
  - "Status: Planned"
assignees:
  - TordLoefgren

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short summary of the problem.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Step-by-step with expected vs. actual result.
      value: |
        1. …
        2. …
        **Expected:** …
        **Actual:** …
