---
name: Idea
description: Early research, spike, or design thought.
title: "[Idea]: "
labels:
  - "Type: Idea"
assignees:
  - TordLoefgren

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What you’re exploring and what you hope to learn or create.
    validations:
      required: true
