---
name: Test
description: Creating unit tests.
title: "[Test]: "
labels:
  - "Type: Test"
assignees:
  - TordLoefgren

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs doing and why.
    validations:
      required: true
