name: Ludus CI (sanity)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: [self-hosted, windows, x64]
    steps:
      - run: echo Runner is reachable
        shell: cmd
